export const categories = [
  {
    categoryName: "Cleaning",
    icon: "Sparkles",
    description: "Deep cleaning, dusting, and organizing",
    color: "from-cyan-500 to-blue-600",
  },
  {
    categoryName: "Plumbing",
    icon: "Droplet",
    description: "Leakages, pipes, and installations",
    color: "from-blue-500 to-indigo-600",
  },
  {
    categoryName: "Electrical",
    icon: "Zap",
    description: "Wiring, fixtures, and repairs",
    color: "from-amber-500 to-orange-600",
  },
  {
    categoryName: "Painting",
    icon: "Paintbrush",
    description: "Wall paint, texture, and touchups",
    color: "from-purple-500 to-pink-600",
  },
  {
    categoryName: "Gardening",
    icon: "Flower",
    description: "Lawn trim, planting, and landscaping",
    color: "from-emerald-500 to-teal-600",
  },
  {
    categoryName: "Appliance Repair",
    icon: "Wrench",
    description: "AC, Fridge, Washing Machines",
    color: "from-rose-500 to-red-600",
  },
  {
    categoryName: "Carpentry",
    icon: "Hammer",
    description: "Furniture, doors, and cabinet repairs",
    color: "from-yellow-600 to-amber-700",
  },
  {
    categoryName: "Pest Control",
    icon: "ShieldAlert",
    description: "Termites, bugs, and pest elimination",
    color: "from-slate-600 to-zinc-800",
  },
];

export const services = [
  {
    id: 1,
    serviceName: "Professional Deep Cleaning",
    category: "Cleaning",
    description: "Complete home deep cleaning with eco-friendly products",
    price: 3500,
    rating: 4.8,
    duration: "3-4 hours",
    image: "https://images.unsplash.com/photo-1584622181563-430f63602d4b?w=500&h=300&fit=crop",
    isAvailable: true,
  },
  {
    id: 2,
    serviceName: "Emergency Plumbing Repair",
    category: "Plumbing",
    description: "24/7 emergency plumbing services for leaks and blockages",
    price: 2500,
    rating: 4.9,
    duration: "1-2 hours",
    image: "https://images.unsplash.com/photo-1585518419759-fdf0f3a89b54?w=500&h=300&fit=crop",
    isAvailable: true,
  },
  {
    id: 3,
    serviceName: "Electrical Wiring & Installation",
    category: "Electrical",
    description: "Professional electrical wiring, repairs, and safety checks",
    price: 4000,
    rating: 4.7,
    duration: "2-3 hours",
    image: "https://images.unsplash.com/photo-1581092918056-0c4c3acd3789?w=500&h=300&fit=crop",
    isAvailable: true,
  },
];
